# 監視対象のOSSリポジトリ設定
repositories:
  - owner: facebook
    name: react
    description: "A declarative, efficient, and flexible JavaScript library for building user interfaces."
  - owner: microsoft
    name: vscode
    description: "Visual Studio Code"
  - owner: golang
    name: go
    description: "The Go programming language"
  - owner: kubernetes
    name: kubernetes
    description: "Production-Grade Container Scheduling and Management"
  - owner: nodejs
    name: node
    description: "Node.js JavaScript runtime"

# RSS設定
rss:
  title: "OSS Merged PRs Feed"
  description: "Recent merged pull requests from popular open source projects"
  link: "https://yokonao.github.io/merged-pr-rss/"
  author:
    name: "RSS Bot"
    email: "bot@example.com"

# GitHub API設定
github:
  max_prs: 100  # リポジトリごとの最大取得PR数
