# 監視対象のOSSリポジトリ設定
repositories:
  - owner: modelcontextprotocol
    name: modelcontextprotocol

# RSS設定
rss:
  title: "OSS Merged PRs Feed"
  description: "Recent merged pull requests from popular open source projects"
  link: "https://yokonao.github.io/merged-pr-rss/"
  author:
    name: "Nao Yokotsuka"
    email: "yokotsukanao@gmail.com"

# GitHub API設定
github:
  max_prs: 100  # リポジトリごとの最大取得PR数
